// Example config for styling classnames
// export const styleConfig = {
// 	[BlockNames.tartar]: ['cardBlock'],
// 	[BlockNames.cooledSeafood]: [
// 		'backgroundBulot',
// 		'transparentBackgroundHeader',
// 	],
// 	[BlockNames.grilledSeafood]: ['cardBlockBordered'],
// 	[BlockNames.plato]: ['filled', 'backgroundShrimp'],
// 	[BlockNames.seafoodPlato]: ['filled', 'backgroundShrimp'],
// 	[BlockNames.mussels]: ['filled', 'blue', 'backgroundMussels'],
// 	[BlockNames.sandwiches]: ['backgroundFish'],
// 	[BlockNames.bowls]: ['cardBlockBordered'],
// 	[BlockNames.surfTurf]: ['cardBlockBordered'],
// 	[BlockNames.steaks]: [''],
// 	[BlockNames.soups]: [''],
// 	[BlockNames.rolls]: ['filled', 'blue', 'backgroundFish'],
// 	[BlockNames.pasta]: ['cardBlockBordered'],
// 	[BlockNames.deserts]: ['filled'],
// 	[BlockNames.drinksGlass]: ['backgroundBulot'],
// 	[BlockNames.groupedAlko]: [
// 		'backgroundBulot',
// 		'cardBlockBordered',
// 		'alkoBlock',
// 	],
// 	[BlockNames.shots]: ['cardBlockBordered'],
// 	[BlockNames.cocktails]: ['cardBlockBordered'],
// 	[BlockNames.beer]: ['filled'],
// 	[BlockNames.drinksBottle]: ['cardBlockBordered'],
// 	[BlockNames.softDrinks]: [''],
// 	[BlockNames.breakfast]: ['cardBlockBordered'],
// };
