export const BlockNames = {
   oysterBar: 'Устричний Бар',
   cooledSeafood: 'Охолоджені морепродукти',
   tartar: 'Тартар',
   grilledSeafood: 'Морепродукти GRILL',
   bowls: 'Боули та салати',
   plato: 'Плато',
   seafoodPlato: 'Seafood плато',
   mussels: 'Мідії',
   sandwiches: 'Бургери та сендвічі',
   avokadoSalad: 'Авокадо салат',
   steaks: 'Стейки із риби',
   soups: 'Супи',
   rolls: 'Роли',
   deserts: 'Десерти',
   drinksGlass: 'Напої келихами',
   beer: 'Пиво',
   drinksBottle: 'Напої пляшками',
   softDrinks: 'Безалкогольні напої',
   breakfast: 'Страви на сніданок',
   sweetBreakfast: 'Солоденького?',
   shots: 'Пий чарками',
   cocktails: 'Коктейлі'
};